In [1]:
import numpy as np

# **Creating array from list**

In [2]:
lists=[1,2,3,4,5,6,7,8,9,0]
print(type(lists))

<class 'list'>


In [3]:
array_list=np.array(lists)
print(type(array_list))
print(array_list)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9 0]


This is 1D array.

# **Creating arrays from scratch**



1.   Create and print an array filled with zeros called zero_array, which has two rows and four columns.
2.   Create and print an array of random floats between 0 and 1 called random_array, which has three rows and six columns.
1.   Using np.arange(), create a 1D array called one_to_ten which holds all integers from one to ten (inclusive).





In [4]:
#1
zero_array=np.zeros((3,4))    #use tuple or list
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#2
random_array=np.random.random((3,6))
random_array

array([[0.84441796, 0.22122259, 0.16110325, 0.6442012 , 0.02124082,
        0.58559355],
       [0.72999206, 0.77742376, 0.95236584, 0.17210273, 0.40575026,
        0.46361623],
       [0.53806093, 0.92799421, 0.75839966, 0.06371502, 0.27922392,
        0.60091554]])

In [6]:
#3
one_to_ten=np.arange(1,11)  #we are not using list.
one_to_ten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **Dimensions in Arrays**

## **0D**

Cheak dimension of array with `.ndim`

In [7]:
zero=np.array(2)
print(zero.ndim)

0


## **1D**

In [8]:
one=np.array([1,2,3,4,5])
print(one.ndim)

1


## **2D**

In [9]:
two=np.array([[1,2],[3,4]])
print(two.ndim)
print(two.shape)
print(two)

2
(2, 2)
[[1 2]
 [3 4]]


## **3D**

In [10]:
three=np.array([[[1,2,4],[3,4,6]],[[11,12,9],[13,14,12]]])
print(three)
print(three.ndim)
print(three.shape)

[[[ 1  2  4]
  [ 3  4  6]]

 [[11 12  9]
  [13 14 12]]]
3
(2, 2, 3)


# **Reshaping arrays**


---


Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
print(arr.ndim)

(12,)
1


### **Reshape From 1-D to 2-D**

In [12]:
arr2D=arr.reshape(12,1)
print(arr2D)
print('Shape:',arr2D.shape)
print('Dimenstion:',arr2D.ndim)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape: (12, 1)
Dimenstion: 2


### **Reshape From 1-D to 3-D**

In [13]:
arr3D=arr.reshape(3,2,2)
print(arr3D)
print('Shape:',arr3D.shape)
print('Dimenstion:',arr3D.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Shape: (3, 2, 2)
Dimenstion: 3


# **Flattening the arrays**


---


Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) or a.flatten() to do this.

In [14]:
print(arr3D.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### **or**

In [15]:
print(arr3D.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# **Data Types**

In [16]:
print(np.arange(1,5).dtype)

int64


## **Creating Arrays With a Defined Data Type**

In [17]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


#specify
newarr=np.array([1, 2, 3, 4], dtype=np.int32)
print(newarr.dtype)

int64
int32


## **Converting Data Type on Existing Arrays**


---


The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [18]:
newarr2=newarr.astype(np.int8)
print(newarr2.dtype)

int8


# **Importing Array**

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [20]:
with open('/content/drive/MyDrive/DataCamp/Data/NYP/tree_census.npy','rb') as f:
          tree_census=np.load(f)
print(tree_census)

[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1198 227387     11      0]
 [  1199 227387     11      0]
 [  1210 227386      6      0]]


Each row of the tree_census 2D array lists information for a different tree: the tree ID, block ID, trunk diameter, and stump diameter in that order.

# **1D Slicing & Indexing array**




1.   Select all rows of block ID data from the 2nd column
2.   Print the first 5 block_ids
1.   Select the 10th block ID from block_ids
2.   Select 5 block IDs from block_ids starting with the 10th ID







In [21]:
#1,2
block_ids=tree_census[:,1]  #indexing
print(block_ids[:5])        #slicing

[501451 501451 501911 501911 501911]


In [22]:
#3
print(block_ids[9])   #indexing

501911


In [23]:
#4
print(block_ids[9:14])    #slicing

[501911 501911 501911 501909 501909]


# **2D Slicing & Indexing array**



1.   Create an array of the first 100 trunk diameters from tree_census
2.   Create an array of trunk diameters with even row indices from 50 to 100 inclusive



In [24]:
#1
trunk=tree_census[:100,2]
trunk

array([24, 20,  3,  3,  4,  4,  4,  4,  4,  3,  3,  4,  2,  2,  3,  4,  4,
        4,  0, 14,  3,  4,  7,  8,  7,  8,  7,  5,  6,  5,  5, 17,  0, 19,
       21, 18,  4,  5,  3,  4,  3,  4, 13, 13, 13,  5,  4,  4,  4, 11,  5,
        4,  5,  8, 51,  7,  4, 15,  3,  8,  6,  6,  3,  4,  3,  2,  3,  3,
        6,  5,  5,  5,  5,  9,  4,  4,  7,  7,  6,  5,  4,  4,  5,  5,  5,
        7,  3,  5,  3,  3,  6,  6,  8,  7,  4,  5,  4,  4,  4,  4])

In [25]:
#2
even=tree_census[50:101:2,2]    #with step 2
even

array([ 5,  5, 51,  4,  3,  6,  3,  3,  3,  6,  5,  5,  4,  7,  6,  4,  5,
        5,  3,  3,  6,  8,  4,  4,  4,  6])

We can also define the step, like this: [start:end:step].

# **Sorting**

In [26]:
with open('/content/drive/MyDrive/DataCamp/Data/NYP/sudoku_game.npy','rb') as f:
          suduku=np.load(f)
print(suduku)

[[0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


In [27]:
#sorting by coloumn axis
sort_suduku_c=np.sort(suduku)
sort_suduku_c

array([[0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

In [28]:
#sorting by row axis
sort_suduku_r=np.sort(suduku,axis=0)
sort_suduku_r

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 4, 2, 0, 0, 3, 1, 0, 1],
       [0, 5, 3, 0, 1, 7, 3, 4, 3],
       [1, 7, 5, 5, 6, 8, 4, 8, 5],
       [6, 9, 6, 9, 8, 9, 6, 9, 7]])

# **Filtering**


---

Returns array of elements


1.   Create a filter array that will return only values higher than 42
2.   Create a filter array that will return only even elements from the original array



In [29]:
#1
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [30]:
#2
arr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = arr[arr % 2 == 0]      #one line code

print(newarr)

[2 4 6]





---


1.   Create an array, largest_tree_data, which contains the row of data on the largest tree in tree_census corresponding to the tree with a diameter of 51.
2.   Slice largest_tree_data to retrieve only the block id of the block the largest tree is located on; save this block id as largest_tree_block_id.

1.   Create an array called trees_on_largest_tree_block which contains data on all trees with the same block ID as the largest tree.










In [31]:
#1
largest_tree=tree_census[tree_census[:,2]==51]
largest_tree

array([[    61, 501882,     51,      0]])

In [32]:
#2
largest_tree_block=largest_tree[:,1]
largest_tree_block

array([501882])

In [33]:
#3
trees_on_large_block=tree_census[tree_census[:,1]==largest_tree_block]
trees_on_large_block

array([[    60, 501882,      8,      0],
       [    61, 501882,     51,      0],
       [    62, 501882,      7,      0],
       [    63, 501882,      4,      0],
       [    64, 501882,     15,      0],
       [    65, 501882,      3,      0],
       [    66, 501882,      8,      0],
       [    67, 501882,      6,      0],
       [    68, 501882,      6,      0],
       [    69, 501882,      3,      0]])

# **NumPy Searching**


---

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

We can also creat arrays from conditions using np.where(condition, replace value if condition meet, replace value if conditin doesn't meet)



1.   Search the index number of tree_census where block_id is 501882.
2.   Create and print a 1D array called trunk_stump_diameters, which replaces a tree's trunk diameter with its stump diameter if the trunk diameter is zero.





In [34]:
#1
ind_trees_on_large_block=np.where(tree_census[:,1]==501882)
ind_trees_on_large_block

(array([53, 54, 55, 56, 57, 58, 59, 60, 61, 62]),)

In [35]:
#2 creating new coloumn
trunk_stump=np.where(tree_census[:,2]==0,tree_census[:,3],tree_census[:,2])
trunk_stump

array([24, 20,  3,  3,  4,  4,  4,  4,  4,  3,  3,  4,  2,  2,  3,  4,  4,
        4,  3, 14,  3,  4,  7,  8,  7,  8,  7,  5,  6,  5,  5, 17, 31, 19,
       21, 18,  4,  5,  3,  4,  3,  4, 13, 13, 13,  5,  4,  4,  4, 11,  5,
        4,  5,  8, 51,  7,  4, 15,  3,  8,  6,  6,  3,  4,  3,  2,  3,  3,
        6,  5,  5,  5,  5,  9,  4,  4,  7,  7,  6,  5,  4,  4,  5,  5,  5,
        7,  3,  5,  3,  3,  6,  6,  8,  7,  4,  5,  4,  4,  4,  4,  6,  5,
        3,  4, 12, 12, 12,  5,  6,  6,  6,  6,  6,  5,  5,  6,  7,  7, 25,
        5,  5,  4,  6,  6,  7, 11,  6, 17, 13, 14, 14, 20, 15, 13,  7,  7,
       10, 17, 14,  4,  6,  7,  8,  7,  7,  6,  7,  5,  2,  2,  2,  2, 26,
       25,  2, 15,  6, 20,  5,  9, 15, 13, 15,  3,  2, 13,  6, 12, 15, 18,
       22, 18, 18, 15, 17,  7,  3,  7,  8,  4, 12, 11, 12,  3,  9, 12, 11,
       10,  8,  6,  6,  7,  7,  3, 15, 12, 12,  4,  5,  5,  5,  4,  4,  5,
        4,  9,  2,  4,  4,  6,  5,  5,  2,  5,  5,  4,  4,  5,  5,  6, 11,
        4,  5,  7,  3, 14

# **Adding and removing data**


---



### **Adding rows**


1.   Print the shapes of tree_census and new_trees to confirm they are compatible to concatenate.
2.   Add rows to tree_census which contain data for the new trees

In [36]:
new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])

In [37]:
#1
print(tree_census.shape,new_trees.shape)

(1000, 4) (2, 4)


It is compatable to connect in row axis. (axis=0)

In [38]:
#2
update=np.concatenate((tree_census,new_trees))
print(update)

[[     3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1210 227386      6      0]
 [  1211 227386     20      0]
 [  1212 227386      8      0]]


### **Adding coloumns**
1.   Print the shapes of tree_census and trunk_stump
2.   Reshape trunk_stump
1.   Concatenate reshaped_trunk_stump to tree_census as the last column

In [39]:
#1
print(tree_census.shape,trunk_stump.shape)

(1000, 4) (1000,)


It is not compatable. Because there is no Dimension compatibility.
trunk_stump is a 1D array and tree_census is 2D.


In [40]:
#2
re=trunk_stump.reshape(1000,1)
print(re.shape)

(1000, 1)


Now it is 2D

In [41]:
#3
update2=np.concatenate((tree_census,re),axis=1)
update2

array([[     3, 501451,     24,      0,     24],
       [     4, 501451,     20,      0,     20],
       [     7, 501911,      3,      0,      3],
       ...,
       [  1198, 227387,     11,      0,     11],
       [  1199, 227387,     11,      0,     11],
       [  1210, 227386,      6,      0,      6]])

### **Deleting with np.delete()**

np.delete(array, which row or col have to del, axis) 



1.   Delete the stump diameter column from tree_census
2.   Found the indices of the trees on block 313879
1.   Delete the rows for trees on block 313879 from no_stumps






In [42]:
#1
no_stump=np.delete(tree_census,3,axis=1)
no_stump.shape

(1000, 3)

In [43]:
#2
a=np.where(tree_census[:,1]==313879)
a

(array([921, 922]),)

In [44]:
#3
tree_no_stump=np.delete(no_stump,[921,922],axis=0)
tree_no_stump.shape

(998, 3)

# **Array Mathematics**

In [45]:
with open('/content/drive/MyDrive/DataCamp/Data/NYP/monthly_sales.npy','rb') as f:
          monthly_sales=np.load(f)
print(monthly_sales)

[[ 4134 23925  8657]
 [ 4116 23875  9142]
 [ 4673 27197 10645]
 [ 4580 25637 10456]
 [ 5109 27995 11299]
 [ 5011 27419 10625]
 [ 5245 27305 10630]
 [ 5270 27760 11550]
 [ 4680 24988  9762]
 [ 4913 25802 10456]
 [ 5312 25405 13401]
 [ 6630 27797 18403]]


Each row in this monthly_sales array represents a month from January to December. The first column has monthly sales data for liquor stores, the second column has data for restaurants, and the last column tracks sales for department stores.



1.   Find monthly total
2.   Find monthlt avg 
1.   Cumulative sum
2.   Add with monthly_sales data




In [54]:
total=monthly_sales.sum(axis=1,keepdims=True)   #keepdims use to make vartical array
avg=monthly_sales.mean(axis=1,keepdims=True)
cumsum=monthly_sales.cumsum(axis=0)
new=np.concatenate((monthly_sales,total,avg),axis=1)
print(new)
n=np.concatenate((monthly_sales,cumsum),axis=0)
n

[[ 4134.         23925.          8657.         36716.
  12238.66666667]
 [ 4116.         23875.          9142.         37133.
  12377.66666667]
 [ 4673.         27197.         10645.         42515.
  14171.66666667]
 [ 4580.         25637.         10456.         40673.
  13557.66666667]
 [ 5109.         27995.         11299.         44403.
  14801.        ]
 [ 5011.         27419.         10625.         43055.
  14351.66666667]
 [ 5245.         27305.         10630.         43180.
  14393.33333333]
 [ 5270.         27760.         11550.         44580.
  14860.        ]
 [ 4680.         24988.          9762.         39430.
  13143.33333333]
 [ 4913.         25802.         10456.         41171.
  13723.66666667]
 [ 5312.         25405.         13401.         44118.
  14706.        ]
 [ 6630.         27797.         18403.         52830.
  17610.        ]]


array([[  4134,  23925,   8657],
       [  4116,  23875,   9142],
       [  4673,  27197,  10645],
       [  4580,  25637,  10456],
       [  5109,  27995,  11299],
       [  5011,  27419,  10625],
       [  5245,  27305,  10630],
       [  5270,  27760,  11550],
       [  4680,  24988,   9762],
       [  4913,  25802,  10456],
       [  5312,  25405,  13401],
       [  6630,  27797,  18403],
       [  4134,  23925,   8657],
       [  8250,  47800,  17799],
       [ 12923,  74997,  28444],
       [ 17503, 100634,  38900],
       [ 22612, 128629,  50199],
       [ 27623, 156048,  60824],
       [ 32868, 183353,  71454],
       [ 38138, 211113,  83004],
       [ 42818, 236101,  92766],
       [ 47731, 261903, 103222],
       [ 53043, 287308, 116623],
       [ 59673, 315105, 135026]])